# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d63e8b50d5e957ee3a0af4cb33b7b27c2f108ccdb824532d7b9d3de731e144649bac6f51f40d7aea0310226ca43172a38b013ebf8e186600c55e1218e1293e

test:
  secret_key_base: 906a9e087b906653983733f46a744d518c35bcb60bfd1209ded1853fa70f9d7ea5fd4ee1693e07d1e77f2fdb7a5e4c9a0f833e9c5c78b6af18b7a05ac810a04e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
